import classNames from "classnames";
import Head from "next/head";
import React from "react";
import styles from "../../styles/Home.module.css";

interface Props {
  title?: string;
  children: React.ReactNode;
  className?: string;
}

export function Layout(props: Props) {
  const { children, className, title = "Denny Scott" } = props;
  return (
    <div
      className={classNames(
        styles.container,
        "bg-[#222] text-stone-50 h-full",
        className
      )}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
      {children}
    </div>
  );
}
